// <auto-generated />
using System;
using Atividade_EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Atividade_EFCore.Migrations
{
    [DbContext(typeof(CidadesContext))]
    [Migration("20211001141538_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Atividade_EFCore.Cidades", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("guid");

                    b.Property<bool>("EstadoCalamidade")
                        .HasColumnType("bit");

                    b.Property<double>("ImpostoSobreProduto")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Nome");

                    b.Property<int>("Populacao")
                        .HasColumnType("int")
                        .HasColumnName("Populacao");

                    b.Property<double>("TaxaCriminalidade")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("Atividade_EFCore.Funcionarios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CidadeId")
                        .HasColumnType("guid");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("funcionarios");
                });

            modelBuilder.Entity("Atividade_EFCore.Funcionarios", b =>
                {
                    b.HasOne("Atividade_EFCore.Cidades", "Cidade")
                        .WithMany("funcionarios")
                        .HasForeignKey("CidadeId");

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("Atividade_EFCore.Cidades", b =>
                {
                    b.Navigation("funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
